# Generated by Django 4.1.1 on 2022-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='imageURL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quize',
            name='questions',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
