# Generated by Django 4.1.1 on 2022-09-24 09:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quize_imageurl_quize_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answare',
            options={'verbose_name_plural': 'وەڵامەکان'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'پرسیارەکان'},
        ),
        migrations.AlterModelOptions(
            name='quize',
            options={'verbose_name_plural': 'وانەکان'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name_plural': 'ئەنجامەکان'},
        ),
        migrations.AlterField(
            model_name='answare',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='وەڵامی دروست'),
        ),
        migrations.AlterField(
            model_name='answare',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_question', to='api.question', verbose_name='prsyar'),
        ),
        migrations.AlterField(
            model_name='answare',
            name='text',
            field=models.CharField(max_length=200, verbose_name='هەڵبژاردن'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_quize', to='api.quize', verbose_name='وانە'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='پرسیار'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='category',
            field=models.CharField(max_length=110, verbose_name='ناو'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='imageURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='وێنە'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='questions',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='ژمارەی پرسیارەکان'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_user', to='api.account'),
        ),
    ]
