# Generated by Django 4.1.1 on 2022-09-26 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answare_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='رێکەوت'),
        ),
        migrations.AddField(
            model_name='question',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='بەروار'),
            preserve_default=False,
        ),
    ]
